spring:
  datasource:
    url: jdbc:sqlserver://pharmaease.database.windows.net:1433;database=pharmaease_totem_db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;Authentication=ActiveDirectoryPassword
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: Arthur  # Substitua pelo seu nome de usuário
    password: 12345678Abc  # Substitua pela sua senha
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true
