spring:
  application:
    name: totem-api

  # Configurações de perfis
  profiles:
    active: dev  # Ou 'prod' dependendo do perfil que você quer ativar

  # Configuração do datasource
  datasource:
    url: https://portal.azure.com/#@fiap.com.br/resource/subscriptions/176d4cd6-7ccc-4c01-9219-035ae619ed3c/resourceGroups/pharme/providers/Microsoft.Sql/servers/pharmaease/databases/pharmaease_totem_db/overview  # URL do banco de dados, pode ser substituído pelo valor diretamente ou pela variável de ambiente
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: RM551283 # Nome de usuário do banco de dados
    password: FIAP@RM_551283  # Senha do banco de dados

  # Configuração do JPA
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true
  flyway:
    locations: classpath:db/migration