name: Build and Deploy Docker Container

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' # Use temurin instead of adopt-openjdk

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t pharmaease-totem .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag pharmaease-totem ${{ secrets.DOCKER_USERNAME }}/pharmaease-totem:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/pharmaease-totem:latest

      - name: Deploy to Windows VM
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VM_IP: ${{ secrets.VM_IP }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem user@$VM_IP << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/pharmaease-totem:latest || true
            docker stop pharmaease-totem || true
            docker rm pharmaease-totem || true
            docker run -d -p 8080:8080 --name pharmaease-totem ${{ secrets.DOCKER_USERNAME }}/pharmaease-totem:latest
          EOF
